# rule identifiers to exclude from running
disabled_rules:
  - class_delegate_protocol
  - discarded_notification_center_observer
  - force_cast
  - force_try
  - identifier_name
  - nesting
  - todo
  - type_name
  - xctfail_message
  # Ideally this we can make rule more customized. Perhaps 4-large.
  - large_tuple

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - first_where
  - for_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - no_extension_access_modifier
  - overridden_super_call
  - override_in_extension
  - prohibited_interface_builder
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded: # paths to ignore during linting. Takes precedence over `included`. These paths are
# relative to the target's build directories.
  - Pods
  - Carthage

line_length: 100

type_body_length:
  warning: 500
  error: 1000

file_length:
  warning: 800
  error: 1200

trailing_comma:
  severity: warning
  mandatory_comma: true

function_body_length:
  warning: 80

empty_count: warning

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube)
