name: Aspire Budgeting Build and Test
on: [push, pull_request]

jobs:
  test:
    name: Build and Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8', 'platform=iOS Simulator,OS=14.1,name=iPhone 9']
        xcode: ['/Applications/Xcode_12.3.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject PLIST files
        run: |
          cd "Aspire Budgeting"; cp ../"Aspire BudgetingTests"/Resources/credentials.plist Resources/; cat Resources/credentials.plist; cd ..

      - name: Install Dependencies
        run: |
          bundle install
          bundle exec pod install

      - name: Code Validation
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger

      - name: Run Tests
        run: bundle exec fastlane unit_test

      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash)
