name: Aspire Budgeting CI/CT
on: push

jobs:
  test:
    name: Build and Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8', 'platform=iOS Simulator,OS=14.1,name=iPhone 9']
        xcode: ['/Applications/Xcode_12.3.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inject PLIST files
        run: |
          cd "Aspire Budgeting"; cp ../"Aspire BudgetingTests"/Resources/credentials.plist Resources/; cat Resources/credentials.plist; cd ..
          cd "Aspire Budgeting"; cp ../"Aspire BudgetingTests"/Resources/instabug.plist Resources/instabug.plist; cd ..